/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YearIndexRouteImport } from './routes/$year/index'
import { Route as WarsWarIdRouteImport } from './routes/wars.$warId'
import { Route as BattlesBattleIdRouteImport } from './routes/battles.$battleId'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'

const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearIndexRoute = YearIndexRouteImport.update({
  id: '/$year/',
  path: '/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarsWarIdRoute = WarsWarIdRouteImport.update({
  id: '/wars/$warId',
  path: '/wars/$warId',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesBattleIdRoute = BattlesBattleIdRouteImport.update({
  id: '/$battleId',
  path: '/$battleId',
  getParentRoute: () => BattlesRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battles': typeof BattlesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/battles/$battleId': typeof BattlesBattleIdRoute
  '/wars/$warId': typeof WarsWarIdRoute
  '/$year/': typeof YearIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battles': typeof BattlesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/battles/$battleId': typeof BattlesBattleIdRoute
  '/wars/$warId': typeof WarsWarIdRoute
  '/$year': typeof YearIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battles': typeof BattlesRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/battles/$battleId': typeof BattlesBattleIdRoute
  '/wars/$warId': typeof WarsWarIdRoute
  '/$year/': typeof YearIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battles'
    | '/api/$'
    | '/battles/$battleId'
    | '/wars/$warId'
    | '/$year/'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battles'
    | '/api/$'
    | '/battles/$battleId'
    | '/wars/$warId'
    | '/$year'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/battles'
    | '/api/$'
    | '/battles/$battleId'
    | '/wars/$warId'
    | '/$year/'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattlesRoute: typeof BattlesRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  WarsWarIdRoute: typeof WarsWarIdRoute
  YearIndexRoute: typeof YearIndexRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$year/': {
      id: '/$year/'
      path: '/$year'
      fullPath: '/$year/'
      preLoaderRoute: typeof YearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wars/$warId': {
      id: '/wars/$warId'
      path: '/wars/$warId'
      fullPath: '/wars/$warId'
      preLoaderRoute: typeof WarsWarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles/$battleId': {
      id: '/battles/$battleId'
      path: '/$battleId'
      fullPath: '/battles/$battleId'
      preLoaderRoute: typeof BattlesBattleIdRouteImport
      parentRoute: typeof BattlesRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BattlesRouteChildren {
  BattlesBattleIdRoute: typeof BattlesBattleIdRoute
}

const BattlesRouteChildren: BattlesRouteChildren = {
  BattlesBattleIdRoute: BattlesBattleIdRoute,
}

const BattlesRouteWithChildren =
  BattlesRoute._addFileChildren(BattlesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattlesRoute: BattlesRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  WarsWarIdRoute: WarsWarIdRoute,
  YearIndexRoute: YearIndexRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
